export const entryDt: entryStore[] = [
  {
    store: "麺屋風花×千代の光酒造",
    name: "発酵味噌らぁめん",
    price: 950,
    image: "/entry/the1st/image09.png",
    votes: 234,
  },
  {
    store: "GOGO宝来軒×竹田酒造店",
    name: "酒粕塩白湯 雅-ミヤビ-",
    price: 1000,
    image: "/entry/the1st/image10.png",
    votes: 203,
  },
  {
    store: "麺屋あごすけ×代々菊醸造",
    name: "ローストビーフの贅沢まぜそば",
    price: 1200,
    image: "/entry/the1st/image11.png",
    votes: 184,
  },
  {
    store: "王華飯店×頚城酒造",
    name: "スパイスキーマラーメン",
    price: 1000,
    image: "/entry/the1st/image12.png",
    votes: 154,
  },
  {
    store: "たんぽぽラーメン×よしかわ杜氏の郷",
    name: "漆黒のイカスミ麺",
    price: 1050,
    image: "/entry/the1st/image13.png",
    votes: 143,
  },
  {
    store: "比他棒×よしかわ杜氏の郷",
    name: "高田ビャンビャン麺",
    price: 1650,
    image: "/entry/the1st/image14.png",
    votes: 112,
  },
  {
    store: "はな禅×丸山酒造場",
    name: "雪むろ酒かすラーメン",
    price: 0,
    image: "/entry/the1st/image15.png",
    votes: 95,
  },
  {
    store: "菜心×妙高酒造",
    name: "雪むろクリスピー担々麺",
    price: 900,
    image: "/entry/the1st/image16.png",
    votes: 50,
  },
  {
    store: "宝来軒参×上越酒造店",
    name: "辛味噌つけ麺〜紅越後〜",
    price: 1050,
    image: "/entry/the1st/image17.png",
    votes: 43,
  },
  {
    store: "食堂ニューミサ×鮎正宗酒造",
    name: "酒かすかんずりみそラテ",
    price: 1300,
    image: "/entry/the1st/image18.png",
    votes: 23,
  },
];
