export const stores = [
  {
    id: 0,
    name: "手打ちらーめん まるとく",
    entry: {
      name: "酒かす鶏ポタージュ",
      price: 1000,
      img: "/top/entry/entry5.jpg",
    },
    main: {
      soup: ["豚骨", "醤油"],
      style: ["ラーメン", "つけ麺"],
      men: ["手打ち太麺"],
      address: ["000-0000", "新潟県新潟市新潟2-22-2"],
      pay: ["現金", "クレジットカード"],
      seat: {
        table: 12,
        counter: 6,
      },
      tel: "00-0000-0000",
      budgetLunch: 1000,
      budgetNight: 1200,
      holiday: ["日", "月"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [8, 7, 10, 5],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
  {
    id: 1,
    name: "春紀",
    entry: {
      name: "酒かすラーメン 白味噌仕立て",
      price: 1000,
      img: "/top/entry/entry6.jpg",
    },
    main: {
      soup: ["豚骨", "醤油"],
      style: ["ラーメン", "つけ麺"],
      men: ["手打ち太麺"],
      address: ["000-0000", "新潟県新潟市新潟2-22-2"],
      pay: ["現金", "クレジットカード"],
      seat: {
        table: 12,
        counter: 6,
      },
      tel: "00-0000-0000",
      budgetLunch: 1000,
      budgetNight: 1200,
      holiday: ["日", "月"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [9, 3, 8, 1],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
  {
    id: 2,
    name: "比他棒（ビーターバン）",
    entry: {
      name: "高田ビャンビャン麺",
      price: 1650,
      img: "/top/entry/entry7.jpg",
    },
    main: {
      soup: ["豚骨", "醤油"],
      style: ["ラーメン", "つけ麺"],
      men: ["手打ち太麺"],
      address: ["000-0000", "新潟県新潟市新潟2-22-2"],
      pay: ["現金", "クレジットカード"],
      seat: {
        table: 12,
        counter: 6,
      },
      tel: "00-0000-0000",
      budgetLunch: 1000,
      budgetNight: 1200,
      holiday: ["日", "月"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [6, 5, 7, 5],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
  {
    id: 3,
    name: "龍馬軒",
    entry: {
      name: "甘えび坦坦麺 酒かす仕立て",
      price: 1250,
      img: "/top/entry/entry8.jpg",
    },
    main: {
      soup: ["豚骨", "醤油"],
      style: ["ラーメン", "つけ麺"],
      men: ["手打ち太麺"],
      address: ["000-0000", "新潟県新潟市新潟2-22-2"],
      pay: ["現金", "クレジットカード"],
      seat: {
        table: 12,
        counter: 6,
      },
      tel: "00-0000-0000",
      budgetLunch: 1000,
      budgetNight: 1200,
      holiday: ["水"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [10, 5, 10, 2],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
  {
    id: 4,
    name: "はな禅",
    entry: {
      name: "雪むろ酒かすラーメン",
      price: 1600,
      img: "/top/entry/entry9.jpg",
    },
    main: {
      soup: ["豚骨", "醤油"],
      style: ["ラーメン", "つけ麺"],
      men: ["手打ち太麺"],
      address: ["000-0000", "新潟県新潟市新潟2-22-2"],
      pay: ["現金", "クレジットカード"],
      seat: {
        table: 12,
        counter: 6,
      },
      tel: "00-0000-0000",
      budgetLunch: 1000,
      budgetNight: 1200,
      holiday: ["月"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [10, 8, 10, 7],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
  {
    id: 5,
    name: "宝来軒総本店",
    entry: {
      name: "菜膳 酒かす味噌タンメン",
      price: 1000,
      img: "/top/entry/entry10.jpg",
    },
    main: {
      soup: ["豚骨", "醤油"],
      style: ["ラーメン", "つけ麺"],
      men: ["手打ち太麺"],
      address: ["000-0000", "新潟県新潟市新潟2-22-2"],
      pay: ["現金", "クレジットカード"],
      seat: {
        table: 12,
        counter: 6,
      },
      tel: "00-0000-0000",
      budgetLunch: 1000,
      budgetNight: 1200,
      holiday: ["日"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [8, 6, 10, 4],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
];
