export const stores: store[] = [
  {
    id: 0,
    name: "手打ちらーめん まるとく",
    entry: {
      name: "酒かす鶏ポタージュ",
      price: 930,
      img: "/top/entry/entry5.jpg",
    },
    main: {
      soup: ["鶏白湯"],
      style: ["ラーメン"],
      men: ["中太ストレート麺"],
      address: ["942-0063", "新潟県上越市下門前770"],
      pay: ["現金"],
      seat: {
        table: 20,
        counter: 6,
      },
      tel: "025-512-6456",
      budgetLunch: 950,
      budgetNight: 950,
      holiday: ["火"],
      images: [
        "/ramen-images/marutoku-mise.jpg",
        "/ramen-images/marutoku-menu.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      battle: [true, false, false, false],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [8, 7, 10, 5],
      storeTime: [true, false, false, true],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
  {
    id: 1,
    name: "春紀",
    entry: {
      name: "酒かすラーメン 白味噌仕立て",
      price: 1000,
      img: "/top/entry/entry6.jpg",
    },
    main: {
      soup: ["塩", "醤油","味噌"],
      style: ["ラーメン","つけ麺"],
      men: ["太麺"],
      address: ["944-0141", "新潟県上越市板倉区田井213-1"],
      pay: ["現金","PayPay"],
      seat: {
        table: 13,
        counter: 5,
      },
      tel: "080-6504-4678",
      budgetLunch: 1000,
      budgetNight: 1000,
      holiday: ["日", "月"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      battle: [true, false, false, false],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [9, 3, 8, 1],
      storeTime: [true, false, false, true],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
  {
    id: 2,
    name: "比他棒（ビーターバン）",
    entry: {
      name: "高田ビャンビャン麺",
      price: 1650,
      img: "/top/entry/entry7.jpg",
    },
    main: {
      soup: ["担々スープ",],
      style: ["ラーメン", "つけ麺"],
      men: ["細麺"],
      address: ["943-0825", "新潟県上越市東本町3-2-59"],
      pay: ["現金", "クレジットカード","PayPay","電子マネー"],
      seat: {
        table: 31,
        counter: 10,
      },
      tel: "025-520-7519",
      budgetLunch: 990,
      budgetNight: 2400,
      holiday: ["月", "第2・4火"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      battle: [true, false, false, false],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [6, 5, 7, 5],
      storeTime: [true, false, false, true],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
  {
    id: 3,
    name: "龍馬軒",
    entry: {
      name: "甘えび坦坦麺 酒かす仕立て",
      price: 1250,
      img: "/top/entry/entry8.jpg",
    },
    main: {
      soup: ["担々スープ","醤油","塩"],
      style: ["ラーメン",],
      men: ["細麺"],
      address: ["943-0884", "新潟県上越市上中田2026"],
      pay: ["現金",],
      seat: {
        table: 24,
        counter: 14,
      },
      tel: "025-526-7751",
      budgetLunch: 1200,
      budgetNight: 1200,
      holiday: ["日"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      battle: [true, false, false, false],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [10, 5, 10, 2],
      storeTime: [true, false, false, true],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
  {
    id: 4,
    name: "はな禅",
    entry: {
      name: "雪むろ酒かすラーメン",
      price: 900,
      img: "/top/entry/entry9.jpg",
    },
    main: {
      soup: ["魚介塩ダレ", "醤油"],
      style: ["ラーメン", "つけ麺"],
      men: ["中太"],
      address: ["943-0882", "新潟県上越市中田原105-8"],
      pay: ["現金",],
      seat: {
        table: 4,
        counter: 4,
      },
      tel: "025-522-9255",
      budgetLunch: 1000,
      budgetNight: 1000,
      holiday: ["月","火"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      battle: [true, false, false, false],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [10, 8, 10, 7],
      storeTime: [true, false, false, true],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
  {
    id: 5,
    name: "宝来軒総本店",
    entry: {
      name: "菜膳 酒かす味噌タンメン",
      price: 1000,
      img: "/top/entry/entry10.jpg",
    },
    main: {
      soup: ["味噌", "醤油","豚骨"],
      style: ["ラーメン","つけ麺"],
      men: ["自家製太麺"],
      address: ["943-0833", "新潟県上越市大町4-1-5"],
      pay: ["現金",],
      seat: {
        table: 12,
        counter: 50,
      },
      tel: "025-523-3415",
      budgetLunch: 800,
      budgetNight: 800,
      holiday: ["木","不定期"],
      images: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
        "/top/entry/entry9.jpg",
      ],
    },
    menu: {
      image: [
        "/top/entry/entry5.jpg",
        "/top/entry/entry6.jpg",
        "/top/entry/entry7.jpg",
        "/top/entry/entry8.jpg",
      ],
      name: ["醤油ラーメン", "塩ラーメン", "豚骨ラーメン", "油そば"],
      battle: [true, false, false, false],
      price: [900, 1000, 1100, 950],
    },
    reputation: {
      star: [8, 6, 10, 4],
      storeTime: [true, false, false, true],
      title: [
        "めちゃくちゃおいしかった！！",
        "ふつう",
        "めちゃくちゃおいしかった！！",
        "そこまでかな",
      ],
      body: [
        "週末家族でお邪魔しました。開店時間前についたのに並んでてびっくりー!!14時台を狙うのがおすすめです。",
        "そこそこおいしいのかなとは感じました。",
        "もう本当においしかったです。最高でした。これから週６で通うつもりです。私のランチはここ以外にあり得ません!!!",
        "よくも悪くもふつうでした。",
      ],
    },
  },
];
