name: Build Test
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - run: npm install
      - run: npm run build
      - run: npm run export

      - uses: actions/upload-artifact@v3
        with: 
          name: out
          path: out/**
          retention-days: 1
  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with: 
          name: out
          path: out
    
      - name: Deploy to Azure VM
        uses: easingthemes/ssh-deploy@v2
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete" # Use rsync to upload the build directory to server
          SOURCE: "out/"
          REMOTE_HOST: "4.216.193.15"
          REMOTE_USER: "azureuser"
          TARGET: "/var/www/html/frontend"

    



    

    